{% set version = "1.1.4" %}

package:
  name: openpisco-split
  version: {{ version }}

source:
  url: https://gitlab.com/openpisco/openpisco/-/archive/{{ version }}/openpisco-{{ version }}.tar.bz2
  sha256: 17a43f954eb5edb26760e3dacec122fb1f10f586a1990c7f83936ca143377e7d

build:
  noarch: python
  number: 0

outputs:
  - name: openpisco-core
    version: {{ version }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - OpenPisco = OpenPisco.QtApp.OpenPiscoGUI:LaunchPiscoGUI
        - OpenPiscoCL = OpenPisco.CLApp.OpenPiscoCL:RunSimulation
      skip_compile_pyc:
        "OpenPiscoParaViewBridge.py"
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - muscat-core =2.2.2
        - python
        - osqp
        - numba
        - qtconsole
        - pyqtgraph
        - PySide2
        - vtk
        - libmed >=4.1.1
        - qt =5
    test:
      imports:
        - OpenPisco
      commands:
        - python -m OpenPisco.CLApp.OpenPiscoCL



  - name: "openpisco"
    version: {{ version }}
    requirements:
      run:
        - openpisco-core
      run_constrained:
        - openpisco-core ={{ version }}
    test:
      imports:
        - OpenPisco
      commands:
        - python -m OpenPisco.CLApp.OpenPiscoCL


about:
  home: https://gitlab.com/openpisco/openpisco
  license_file: LICENSE
  license: LGPL-3.0-only
  license_family: LGPL
  summary: A toolbox for topology optimization
  description: |
    OpenPisco is a research and development platform devoted to topology
    optimization relying on the level set method.
  doc_url: https://openpisco.readthedocs.io/
  dev_url: https://gitlab.com/openpisco/openpisco

extra:
  recipe-maintainers:
    - fbordeu
    - cnrdn
    - daviddanan
